source 'http://rubygems.org'

gem 'rails', '2.3.5'
gem 'rake',  '0.8.7'
gem 'fastercsv'
gem 'rcov'
gem 'rdoc',  '3.8'
gem 'warden', '0.10.7'
gem 'devise', '1.0.11'
gem 'will_paginate', '2.3.16'
gem 'json'
gem 'settingslogic'
gem 'rest-client','1.6.7'
gem 'mysql2', '< 0.3'
gem 'mechanize'
gem 'pdfkit'
gem 'mime-types', '1.23'
gem 'passenger','4.0.8'
gem 'nokogiri', '1.5.5'
