production:
  adapter: mysql
  database: bart
  username: root
  password: letusout
  host: localhost

development:
  adapter: mysql
  database: bart
  username: root
  password: letusout
  host: localhost

test: &TEST
  adapter: mysql
  database: openmrs_test
  username: root
  password: letusout
  host: localhost

cucumber:
  <<: *TEST

migration:
  adapter: mysql
  database: openmrs_qech
  username: root
  password: letusout
  host: localhost

healthdata:
  adapter: mysql
  database: healthdata
  username: root
  password: letusout
  host: localhost
