--- 
cwd: /home/blessings/Work/Radiology
log_file: /home/blessings/Work/Radiology/log/mongrel.log
port: 3000
environment: production
address: 0.0.0.0
pid_file:  /home/blessings/Work/Radiology/tmp/pids/mongrel.pid
servers: 1 
